// <auto-generated />
using System;
using EveryoneToTheHackathon.Domain.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EveryoneToTheHackathon.Domain.Migrations._2024
{
    [DbContext(typeof(HackathonContext))]
    partial class HackathonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeId", "Role");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.Hackathon", b =>
                {
                    b.Property<Guid>("HackathonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HarmonicMean")
                        .HasPrecision(16, 12)
                        .HasColumnType("decimal(16,12)");

                    b.HasKey("HackathonId");

                    b.ToTable("Hackathons");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.HackathonDreamTeam", b =>
                {
                    b.Property<Guid>("HackathonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TeamLeadId")
                        .HasColumnType("int");

                    b.Property<int>("JuniorId")
                        .HasColumnType("int");

                    b.Property<string>("JuniorRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeamLeadRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HackathonId", "TeamLeadId", "JuniorId");

                    b.HasIndex("JuniorId", "JuniorRole");

                    b.HasIndex("TeamLeadId", "TeamLeadRole");

                    b.ToTable("HackathonDreamTeams");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.HackathonEmployeeWishListMapping", b =>
                {
                    b.Property<Guid>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("HackathonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MappingId");

                    b.HasIndex("HackathonId");

                    b.HasIndex("EmployeeId", "EmployeeRole", "HackathonId")
                        .IsUnique();

                    b.ToTable("HackathonEmployeeWishListMappings");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.WishList", b =>
                {
                    b.Property<Guid>("WishListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MappingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PreferenceValue")
                        .HasColumnType("int");

                    b.Property<int>("PreferredEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PreferredEmployeeRole")
                        .HasColumnType("int");

                    b.HasKey("WishListId");

                    b.HasIndex("MappingId");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.HackathonDreamTeam", b =>
                {
                    b.HasOne("EveryoneToTheHackathon.Domain.Entities.Hackathon", "Hackathon")
                        .WithMany("HackathonDreamTeams")
                        .HasForeignKey("HackathonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EveryoneToTheHackathon.Domain.Entities.Employee", "Junior")
                        .WithMany("DreamTeamJuniors")
                        .HasForeignKey("JuniorId", "JuniorRole")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EveryoneToTheHackathon.Domain.Entities.Employee", "TeamLead")
                        .WithMany("DreamTeamLeads")
                        .HasForeignKey("TeamLeadId", "TeamLeadRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hackathon");

                    b.Navigation("Junior");

                    b.Navigation("TeamLead");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.HackathonEmployeeWishListMapping", b =>
                {
                    b.HasOne("EveryoneToTheHackathon.Domain.Entities.Hackathon", "Hackathon")
                        .WithMany("HackathonEmployeeWishListMappings")
                        .HasForeignKey("HackathonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EveryoneToTheHackathon.Domain.Entities.Employee", "Employee")
                        .WithMany("HackathonEmployeeWishListMappings")
                        .HasForeignKey("EmployeeId", "EmployeeRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Hackathon");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.WishList", b =>
                {
                    b.HasOne("EveryoneToTheHackathon.Domain.Entities.HackathonEmployeeWishListMapping", "HackathonEmployeeWishListMappings")
                        .WithMany("WishLists")
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HackathonEmployeeWishListMappings");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.Employee", b =>
                {
                    b.Navigation("DreamTeamJuniors");

                    b.Navigation("DreamTeamLeads");

                    b.Navigation("HackathonEmployeeWishListMappings");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.Hackathon", b =>
                {
                    b.Navigation("HackathonDreamTeams");

                    b.Navigation("HackathonEmployeeWishListMappings");
                });

            modelBuilder.Entity("EveryoneToTheHackathon.Domain.Entities.HackathonEmployeeWishListMapping", b =>
                {
                    b.Navigation("WishLists");
                });
#pragma warning restore 612, 618
        }
    }
}
